### ISSUE TITLE
CAN NOT RUN THE simulate.html

### ISSUE THREAD

**Issue by wei1224hf** [valenorf/KUKA-KR5-Simulator#2]
1 the ScrittaKuka can not added to the fourth, because the fourth is not loaded yet.
So I chaged the code:
				loader.load('KR5_850/Fourth.stl', function (geometry) {
					var material = new THREE.MeshPhongMaterial({ color: 0x404040, specular: 0x111111, shininess: 60,map: text});
					fourth = new THREE.Mesh( geometry, material);
					fourth.position.set(-75, 0, -335-360-90);
					//fourth.castShadow = true;
					//fourth.receiveShadow = true;

					rt_block.add(fourth);
					
					
					loader.load('KR5_850/ScrittaKuka.stl', function (geometry) {
						var material = new THREE.MeshPhongMaterial({ color: 0xcc0000, specular: 0x111111, shininess: 60,map: text});
						var scritta = new THREE.Mesh( geometry, material);
						//scritta.castShadow = true;
						//scritta.receiveShadow = true;

						fourth.add(scritta);
					});
				
				});

2  can not render

**Comment by wei1224hf** [comment]
OK ， can run the file now.
have to comment some lines;
I upload an img to show which lines.
![qq 20180715120922](https://user-images.githubusercontent.com/178312/42730482-03446856-8828-11e8-96f6-2e55b4d457f9.png)



then the file runs like:

![qq 20180715121052](https://user-images.githubusercontent.com/178312/42730492-270a2c6c-8828-11e8-9450-5de35f5c233c.png)

**Comment by giulioturrisi** [comment]
Sorry for the delay!
So problem solved now?
